version: 2.1

jobs:
  build: # over here is the job name
    docker:
      - image: docker/whalesay
    steps:
      - run: docker run docker/whalesay cowsay boo

workflows:
  say_hello:
    jobs:
      - build