version: 2.1

jobs:
  build: # over here is the job name
    docker:
      - image: cimg/docker:20.10.7
    steps:
      - checkout
      - run:
          name: build docker image
          command: docker build -t rohitdarekar816/rohit-portfolio:latest .
      - run:
          name: push docker image
          command: docker push rohitdarekar816/rohit-portfolio:latest


workflows:
  say_hello:
    jobs:
      - build